name: Docker Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application with Docker Compose
    runs-on: self-hosted

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

   
      - name: Deploy with Docker Compose
        run: |
          cd /var/www/myapp/_work/MicroService-MongoDB/MicroService-MongoDB
          git pull origin main
          docker compose up -d --build prod